<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-01-08T20:38:59+05:30
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      server_timezone
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'server_timezone' => 'Asia/Kolkata',
];
