<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-02-04T20:51:02+05:30
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.latest_version
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.5.4',
    'version_db_installed' => '20200609145307',
    'misc' => [
        'login_redirect' => 'HOMEPAGE',
        'access_entity_updated' => 1610118539,
        'latest_version' => '8.5.4',
        'do_page_reindex_check' => false,
        'user_timezones' => true,
        'login_redirect_cid' => 0,
    ],
    'cache' => [
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => false,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
        'clear' => [
            'thumbnails' => true,
        ],
    ],
    'theme' => [
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ],
    'seo' => [
        'redirect_to_canonical_url' => 0,
        'url_rewriting' => true,
    ],
    'permissions' => [
        'model' => 'advanced',
    ],
];
