<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2021-02-04T19:21:06+05:30
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.user.display_account_menu
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'concretesite',
            'editor' => [
                'concrete' => [
                    'enable_filemanager' => true,
                    'enable_sitemap' => true,
                ],
                'ckeditor4' => [
                    'plugins' => [
                        'selected' => [
                            'concrete5filemanager',
                            'concrete5inline',
                            'concrete5uploadimage',
                            'dialogadvtab',
                            'divarea',
                            'floatingspace',
                            'normalizeonchange',
                            'resize',
                            'toolbar',
                            'wysiwygarea',
                            'a11yhelp',
                            'autogrow',
                            'basicstyles',
                            'colorbutton',
                            'colordialog',
                            'concrete5link',
                            'concrete5styles',
                            'contextmenu',
                            'elementspath',
                            'emoji',
                            'enterkey',
                            'entities',
                            'font',
                            'format',
                            'horizontalrule',
                            'htmlwriter',
                            'image',
                            'indentblock',
                            'indentlist',
                            'justify',
                            'list',
                            'liststyle',
                            'magicline',
                            'preview',
                            'removeformat',
                            'showblocks',
                            'showborders',
                            'sourcedialog',
                            'sourcearea',
                            'stylescombo',
                            'tab',
                            'table',
                            'tableresize',
                            'tableselection',
                            'tabletools',
                            'undo',
                            'wsc',
                        ],
                    ],
                ],
            ],
            'seo' => [
                'canonical_url' => '',
                'canonical_url_alternative' => '',
                'canonical_tag' => [
                    'enabled' => true,
                ],
            ],
            'user' => [
                'profiles_enabled' => false,
                'display_account_menu' => true,
                'gravatar' => [
                    'enabled' => true,
                    'max_level' => 'g',
                    'image_set' => '404',
                ],
            ],
        ],
    ],
];
